# Generated by Django 5.2.4 on 2025-07-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(help_text='This is the actual message being sent with the notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the notification was created'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Determines if the notification has been seen by the user'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, help_text="This is a routing link to take user to where they'll take an action based on the notification", null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_to_id',
            field=models.IntegerField(help_text='This is the id number of the object for which the notification was created'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_type',
            field=models.CharField(choices=[('mentorship_requested', 'Mentorship Requested'), ('request_accepted', 'Request Accepted'), ('mentorship_recommendation', 'Mentorship Recommendation')], help_text='This refers to the type of notification', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('mentorship_requested', 'Mentorship Requested'), ('request_accepted', 'Request Accepted'), ('mentorship_recommendation', 'Mentorship Recommendation')], max_length=50),
        ),
    ]
