# Generated by Django 5.2.4 on 2025-07-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_delivered',
            field=models.BooleanField(default=False, help_text='This confirms if the notification was sent to the user'),
        ),
    ]
