# Generated by Django 5.2.4 on 2025-07-15 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='behance_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dribble_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='twitter_url',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Tell us a little bit about yourself')),
                ('title', models.CharField(help_text="What's the user's current job title?", max_length=255)),
                ('career_summary', models.TextField(blank=True, help_text='What has this user done over the course of their career?', null=True)),
                ('experience_level', models.CharField(choices=[('beginner', 'BEGINNER'), ('intermediate', 'INTERMEDIATE'), ('expert', 'EXPERT')], max_length=15)),
                ('career_goal', models.CharField(help_text='Where does the user want to be in 5 years?', max_length=255)),
                ('industry', models.CharField(choices=[('tech', 'Tech'), ('design', 'Design'), ('business', 'Business'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('legal', 'Legal'), ('engineering', 'Engineering'), ('arts', 'Arts'), ('other', 'Other')], help_text='Where does this user work or intend to work', max_length=50)),
                ('role', models.CharField(blank=True, choices=[('mentor', 'MENTOR'), ('mentee', 'MENTEE')], help_text='Is the user a mentor or mentee?', max_length=6)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('dribble_url', models.URLField(blank=True, null=True)),
                ('behance_url', models.URLField(blank=True, null=True)),
                ('portfolio_site', models.URLField(blank=True, null=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='skills_list', to='mentorship.skills')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
