# Generated by Django 5.2.4 on 2025-07-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_behance_url_remove_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(help_text="What's the user's current job title?", max_length=500),
        ),
    ]
