# Generated by Django 5.2.4 on 2025-07-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='career_goal',
            field=models.CharField(help_text='Where does the user want to be in 5 years?', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(help_text="What's the user's current job title?", max_length=100),
        ),
    ]
